DDCE-4195: Update CSP
hmrc/register-estate-details-frontend pull request #65
Opened 2023-08-29 15:16 UTC by MRBeresford

2023-09-05 13:34 UTC, matthewwardcap requested changes
Perfect, one small change with an import

2023-09-06 11:35 UTC, MRBeresford commented on project/AppDependencies.scala
>      play.sbt.PlayImport.ws,
Done 👍

2023-09-06 11:36 UTC, MRBeresford commented on project/AppDependencies.scala
>      play.sbt.PlayImport.ws,
Done 👍

2023-09-06 12:57 UTC, matthewwardcap approved these changes

2023-09-06 12:58 UTC, merged